### ISSUE TITLE
Send to gzip instead of Remote Host

### ISSUE THREAD

**Issue by kennyparsons** [gbytedev/zfsbud#13]
Currently, I snapshot with zfsbud and manually send it to a file with 
```
zfs send pool/filesystem/userdata@zfsbud_20210803154610 | gzip > /path/to/output
```

This allows me to upload the file to the cloud as just a plain file. Is it possible to do this with zfsbud? (i.e. not using the `--rsh` flag). I'd prefer to use zfsbud, as it will automatically handle sending all snapshots not currently found on the target.

**Comment by gbytedev** [comment]
So you'd like to query the target for non-existing snapshots but send these snapshots to a file instead of the target pool?

`-s` will send snapshots to a local pool and adding `-rsh` will send them to a remote pool. These commands have no output that could be piped I'm afraid. I struggle to see how this could be implemented in the comparably high level UI of this script, but if you have any ideas, let me know.

**Comment by kennyparsons** [comment]
Thanks for the info, @gbytedev . Here's some more backstory:
I have 10 VMs, all running ZFS pools, which store "critical" data (none of it life altering, just a lot of my own hard work into setting it up). I plan on using zfsbud to do what it advertises and ship my snapshots off to a dedicated VM with target backup pools. However, this VM is just running on the same infra right now, so it would be subject to the same disaster scenario as the original VMs. And since RAID (and ZFS) is not a backup, I'm trying to plan out a backup plan. 

The current plan is to use the native ZFS send command to send the snapshot to a file. Easily accomplished with 
```bash 
zfs send the_snapshot_name | gzip > /path/to/ouputname.gz
```
This gzipped file can then easily be backed up to the cloud for an offsite backup with any storage provider (drive, s3, b2, etc) since it's just a file.

Where zfsbud would come in:
- [x] create organized snapshots on a cron schedule
- [ ] sending said snapshots somewhere (no need to receive at this juncture). 

My current planned process is to use zfsbud to make the snapshot, but I need to then manually send the snapshot with the command above AND be sure to send all snapshots that don't exist on the target (i.e. not already sent to a gz file on the filesystem/block storage/rclone mount, etc). 

Hope that makes sense.
