### ISSUE TITLE
info/doc: depends on GNU date

### ISSUE THREAD

**Issue by evert-mouw** [gbytedev/zfsbud#18]
Only GNU date has the `-d` option. When I tried this script on OmniOS (an Illumos / Solaris derived system) I ran into problems. Maybe add this to the documentation as those Solaris based systems all have ZFS; it was invented there.
Note that I could get it working by replacing `date` with `/usr/gnu/bin/date`.
Probably nobody is affected by this (who is using such systems anyway, although I like it for my old backup server) but one possible solution would be to replace `date` with `$DATECMD` and set `$DATECMD` to the correct binary (or at least make it very easy to change).

PS: Thanks for your script! Now using it on my home/hobby backup server running OmniOS!

**Comment by gbytedev** [comment]
Feel free to provide a patch :)

**Comment by gbytedev** [comment]
Thank you.
