### ISSUE TITLE
add timeout

### ISSUE THREAD

**Issue by crispyduck00** [gbytedev/zfsbud#23]
Hi,

just started to try/test zfsbud after znapzend, syncoid, zrep,... Great work. simple and clean.

I am testing different fail scenarios, and saw that if the remote host is not reachable zfsbug is stuck. 
Thought I can simply add "timeout 5 or whatever to --rsh, but seems this is not working .

Is there a way to do this e.g. with --rsh? Or can some timeout be added to the code?

I don't want to run the whole script with timeout, As if some send/recv will take longer it will also time out.

Br,
cd

**Comment by gbytedev** [comment]
Thanks for the compliment!

Try adding the ConnectTimeout option (in seconds) to the ssh bit: `--rsh "ssh user@server -p1234 -o ConnectTimeout=10"`

Let me know if that works.

**Comment by crispyduck00** [comment]
Yes I tested this already. I now also know why it did not work yesterday. 
I made ssh persistent between my hosts to speed up some things with adding following to ~/.ssh/config
```
Host 10.88.88.61 10.88.88.62 10.88.88.63
    ControlPath ~/.ssh/control-master-%r@%h:%p
    ControlMaster auto
    ControlPersist 3600
```

Any way to still terminate zfsbud if connection can not be made? Tried `--rsh "timeout 5 ssh user@server -p1234"` but seems this does not work here.

Br
