### ISSUE TITLE
instruction for rollback

### ISSUE THREAD

**Issue by crispyduck00** [gbytedev/zfsbud#24]
What is the best way to rollback to a point in time snapshot on the main (sending) host?

Is there maybe also a way to do a rollback only on the main host and this is also replicated?

Br

**Comment by gbytedev** [comment]
Rolling back is a [simple zfs command](https://docs.oracle.com/cd/E19253-01/819-5461/gbcxk/index.html) and I don't know how zfsbud could simplify it further.

> Is there maybe also a way to do a rollback only on the main host and this is also replicated?

I believe rolling back the source (assuming you roll back to a snapshot that is also available on the destination), then snapshotting the source and then replicating to destination will destroy snapshots on the destination between the rolled back source snapshot and the new snapshot:
```
zfs rollback some/dataset@zfsbud_123
zfsbud -c -s destination some/dataset
```

But test with non-critical data. ;)

**Comment by crispyduck00** [comment]
How ZFS Rollback works is clear, the question is what is the best/clean way to do it in combination with zfsbug?

I just tested it again:
```
zfs rollback some/dataset@zfsbud_123
zfsbud -c -s destination some/dataset
```
works directly on the main dataset "some/dataset" but doing a rollback on any sub datasets of some/datasets with -c -R fails:
```
cannot receive new filesystem stream: destination has snapshots (eg. some/dataset/subdataset@zfsbud_20220317052219)
must destroy them to overwrite it
```

Thats the reason for this question. How to do a rollback of any dataset if needed.

**Comment by gbytedev** [comment]
Closing as per lack of activity.
